name: flexi
description: >-
  Beside predefined breakpoint systems, such as Material,
  you can create your fixed and responsive layout for different grid types:
  Manuscript, Columns, Modular and Baseline.
version: 0.3.1
homepage: https://github.com/zenonine/flexi
documentation: https://github.com/zenonine/flexi/tree/master/flexi
issue_tracker: https://github.com/zenonine/flexi/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
  meta: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  zenonine_lints: ^0.1.0
