name: flexi_example
description: Flexi example
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flexi: any
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  zenonine_lints: ^0.1.0

dependency_overrides:
  flexi:
    path: ../../flexi

flutter:
  uses-material-design: true