name: flexi_material_example
description: Flexi example - material layout
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flexi: any
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

dependency_overrides:
  flexi:
    path: ../../flexi

flutter:
  uses-material-design: true
