name: Publish

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: flexi

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1

      - run: flutter config --no-analytics
      - run: flutter --version

      # TODO: fail if current tag and pubspec version is matched
      # TODO: fail if publish --dry-run has warnings/errors

      - name: Verify puslishing
        run: flutter packages publish --dry-run

      - name: Setup Pub Credentials
        shell: bash
        env:
          PUB_DEV_PUBLISH_ACCESS_TOKEN: ${{ secrets.PUB_DEV_PUBLISH_ACCESS_TOKEN }}
          PUB_DEV_PUBLISH_REFRESH_TOKEN: ${{ secrets.PUB_DEV_PUBLISH_REFRESH_TOKEN }}
          PUB_DEV_PUBLISH_ID_TOKEN: ${{ secrets.PUB_DEV_PUBLISH_ID_TOKEN }}
          PUB_DEV_PUBLISH_EXPIRATION: ${{ secrets.PUB_DEV_PUBLISH_EXPIRATION }}
        run: |
          sh ./pub_dev_login.sh

      - name: Puslish package
        run: flutter packages publish
